pr - status:\ unreviewed:
  - any: ['*']

type:\ Forum Helpers List:
  - forumhelpers/curators.json
  - forumhelpers/managers.json
  
type:\ documentation:
  - README.md
  - LICENSE
  - .github/**/*
  - contributors/contributors.html
