unreviewed:
  - any: ['*']

Forum Helpers List:
  - forumhelpers/curators.json
  - forumhelpers/managers.json
  
documentation:
  - README.md
  - LICENSE
  - .github/**/*
  - contributors/contributors.html
